### ISSUE TITLE
Circuit boards

### ISSUE THREAD

**Issue by smebberson** [StuckAtPrototype/Racer#17]
Are there only services that will allow me to have one the PCB printed with all of the electrical components in place? Are all of the files available for this project that would be needed for such a service?

I have no idea about how to make the final circuit board with everything soldered in place, but I would like to try and build this project.

I'm a software guy with some ESP32 programming experience

**Comment by StuckAtPrototype** [comment]
Everything necessary is within the repo, that said, I will generate placement files which will make it much easier. I am happy that you want to build it! I would love to see it once you are done :) Also, feel free to open a thread in the discussions if you need any help! thanks for the support
