### ISSUE TITLE
Consider adding a license file to the project

### ISSUE THREAD

**Issue by JeremiahSecrist** [StuckAtPrototype/Racer#18]
It's important to choose a license for your files so that others understand how they can use your work. The license also protects you, the creator, from liability and misuse.

When a license isn’t clear, several questions often arise:

Can I use it commercially?
Do I have to share my source code?
etc...

check out: https://choosealicense.com/licenses/

**Comment by StuckAtPrototype** [comment]
The project is licensed under Apache 2.0. The license is listed in the Readme. I will consider adding an additional file. Thanks!
