### ISSUE TITLE
request for the charging circuit design and details used in the project 

### ISSUE THREAD

**Issue by nithinmathewjoji** [StuckAtPrototype/Racer#21]
# Request for LiPo Charger Circuit Design details

Dear **Mr. StuckAtPrototype**,

Kindly provide the circuit schematic, explaining:
   - The connections between components.
   - The placement of safety components like diodes and fuses.
   - Input/output terminals and how they interface with the battery.

**Comment by blubbsy** [comment]
Hi,

is there a reason why to use a GPT text for asking this? But to answer your question: For the project simply the Microchip MCP73833 is used and in the datasheet you find this picture with values:

![image](https://github.com/user-attachments/assets/2745f45f-e329-48a3-befa-1953189767b9)

**Comment by nithinmathewjoji** [comment]
Naa I'm just too lazy to type the whole thing dude 😆 🤣

**Comment by DeepCoreSystem** [comment]
Open the KiCad project and you'll find the schematic

**Comment by StuckAtPrototype** [comment]
everything needed is in the files. closing this out
