### ISSUE TITLE
Question on Racer outside shell

### ISSUE THREAD

**Issue by aushe02** [StuckAtPrototype/Racer#22]
I was looking at the mechanical step files and noticed there isn't a file for the outside shell of the Racer that goes over the enclosure, like in the picture below. I was wondering if you 3D printed that part. If you did, could you upload the file? 

<img width="579" alt="Racer outside shell" src="https://github.com/user-attachments/assets/bd3e07c6-ab38-4990-ae4c-ad338bede72a">

**Comment by StuckAtPrototype** [comment]
The original body does not fit the new version and at this point id have to dig deep to find the original body files. But, yes it was printed on an SLA printer
