### ISSUE TITLE
Bom for thumbtroller is missing

### ISSUE THREAD

**Issue by Mk-arc** [StuckAtPrototype/Racer#24]
I couldnt find the bom for the controller. Could you also add it?

**Comment by FrerichsJacob** [comment]
It's in the Thumbtroller repository!
https://github.com/StuckAtPrototype/Thumbtroller/tree/master/hardware

**Comment by StuckAtPrototype** [comment]
closing this out. its here https://github.com/StuckAtPrototype/Thumbtroller/blob/master/hardware/controller-v0.2-BOM.csv
