### ISSUE TITLE
Please add BOMs

### ISSUE THREAD

**Issue by alexspurling** [StuckAtPrototype/Racer#4]
It would be helpful to include BOM files for the PCB (including the motors) so we know which parts to order (same goes for the controller project).

**Comment by tobiasoort** [comment]
(this way more novice users can use a service like JLCPCB to order the completed PCB and get going quickly too)

**Comment by Rubines** [comment]
Thank you for sharing this fun project!
Please add the motor data, do you have a link where I could source them ?

**Comment by mianzhi** [comment]
> Thank you for sharing this fun project! Please add the motor data, do you have a link where I could source them ?

I guess they are "6 mm geared coreless motor, 1200 rpm nominal speed at 3V". @StuckAtPrototype thanks for sharing the project, please correct me if i was wrong.

**Comment by StuckAtPrototype** [comment]
@mianzhi thats correct!

I will be sharing a BOM late tonight!

for now, you can find the motors by searching "6mm planetary motors 1200 rpm"

**Comment by Rubines** [comment]
Thank you both for your help!
@mianzhi @StuckAtPrototype

**Comment by StuckAtPrototype** [comment]
initial BOM added for the racer. I still have the sensor board and the controller to do, but that will have to wait until tomorrow 👍

**Comment by hazerty565** [comment]
hi, I would like to know whats is motor it is use? have you got a reference? Thank you

**Comment by StuckAtPrototype** [comment]
All BOMs are in! if there are any problems, lets open a new issue. closing this out 🎉
